###
GET http://localhost:3000/api/users/10

###
GET http://localhost:3000/api/roles

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@doe.com"
}

POST http://localhost:3000/api/products
Content-Type: application/json

{
  "code": "10001", 
  "name": "Super Coffee",
  "price": 50.5,
  "cost": 30.25,
  "remark": "สินค้าขายดี"
}

###
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "code": "1000", 
  "name": "Super Coffee",
  "price": 50.5,
  "cost": 30.25
}

###
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "code": "10002",
  "name": "Tea",
  "price": "แพงจัง",
  "cost": 200.25
}

###
GET http://localhost:3000/api/midterm

###
POST http://localhost:3000/api/midterm
Content-Type: application/json

{
  "Date": "2023-12-01",
  "Time": "10:30",
  "Status": "รอการยืนยัน",
  "Notes": "สอบวิชา Web Programming"
}

###
GET http://localhost:3000/api/midterm/1001

###
PUT http://localhost:3000/api/midterm/1001
Content-Type: application/json

{
  "Date": "2023-12-01",
  "Time": "10:30",
  "Status": "ยืนยันแล้ว",
  "Notes": "สอบเสร็จแล้ว (แก้ไขสถานะ)"
}

###
DELETE http://localhost:3000/api/midterm/1001