###
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "code": "10002",
  "name": "Tea",
  "price": "แพงจัง",
  "cost": 200.25
}

###
GET http://localhost:3000/api/medical

### 
POST http://localhost:3000/api/medical
Content-Type: application/json

{
  "Date": "2024-02-14",
  "Time": "10:30",
  "Status": "รอการยืนยัน",
  "Notes": "นัดตรวจสุขภาพฟัน (Dental Care)"
}

### 
GET http://localhost:3000/api/medical/HN-1001

### 
PUT http://localhost:3000/api/medical/HN-1001
Content-Type: application/json

{
  "Date": "2024-02-14",
  "Time": "10:30",
  "Status": "ยืนยันแล้ว",
  "Notes": "ยืนยันการนัดหมายเรียบร้อย"
}

### 
DELETE http://localhost:3000/api/medical/HN-1001